//! Independent fixture and writer oracles for the supported PLY subset.
//!
//! Header and binary-value checks below intentionally do not call the product
//! PLY reader, so writer/reader agreement alone cannot hide a shared defect.

use std::sync::Arc;

use pcx_cli::{
    core::{
        Destination, FrameSelector, JobSpec, Planner, SourceSpec,
        point::{
            MaterializationBudget, PointBatch, PointColumn, PointDimensions, PointField,
            PointFieldSemantic, PointFrameMetadata, PointSchema, PrimitiveType, Timestamp,
        },
    },
    ply::{self, Encoding, Reader},
};

const ASCII: &[u8] = include_bytes!("fixtures/valid/scalar-vertices-ascii.ply");
const LITTLE: &[u8] = include_bytes!("fixtures/valid/scalar-vertices-binary-little-endian.ply");
const BIG: &[u8] = include_bytes!("fixtures/valid/scalar-vertices-binary-big-endian.ply");

fn split_header(bytes: &[u8]) -> (&str, &[u8]) {
    let marker = b"end_header\n";
    let offset = bytes
        .windows(marker.len())
        .position(|window| window == marker)
        .expect("end_header")
        + marker.len();
    (
        std::str::from_utf8(&bytes[..offset]).expect("ASCII header"),
        &bytes[offset..],
    )
}

fn expected_header(encoding: &str) -> String {
    format!(
        "ply\nformat {encoding} 1.0\ncomment generated by pcx\nelement vertex 2\n\
property char signed_byte\nproperty uchar unsigned_byte\nproperty short signed_short\n\
property ushort unsigned_short\nproperty int signed_int\nproperty uint unsigned_int\n\
property float x\nproperty double time\nend_header\n"
    )
}

fn assert_schema_and_values(batch: &PointBatch) {
    let fields: Vec<_> = batch
        .schema()
        .fields()
        .iter()
        .map(|field| {
            (
                field.name(),
                field.primitive(),
                field.count(),
                field.semantic(),
            )
        })
        .collect();
    assert_eq!(
        fields,
        [
            ("signed_byte", PrimitiveType::I8, 1, None),
            ("unsigned_byte", PrimitiveType::U8, 1, None),
            ("signed_short", PrimitiveType::I16, 1, None),
            ("unsigned_short", PrimitiveType::U16, 1, None),
            ("signed_int", PrimitiveType::I32, 1, None),
            ("unsigned_int", PrimitiveType::U32, 1, None),
            ("x", PrimitiveType::F32, 1, Some(PointFieldSemantic::X)),
            ("time", PrimitiveType::F64, 1, None),
        ]
    );
    assert_eq!(batch.dimensions(), PointDimensions::new(2, 1).unwrap());
    assert_eq!(
        batch.column("signed_byte"),
        Some(&PointColumn::I8(vec![-1, i8::MIN]))
    );
    assert_eq!(
        batch.column("unsigned_byte"),
        Some(&PointColumn::U8(vec![2, u8::MAX]))
    );
    assert_eq!(
        batch.column("signed_short"),
        Some(&PointColumn::I16(vec![-300, i16::MIN]))
    );
    assert_eq!(
        batch.column("unsigned_short"),
        Some(&PointColumn::U16(vec![400, u16::MAX]))
    );
    assert_eq!(
        batch.column("signed_int"),
        Some(&PointColumn::I32(vec![-50_000, i32::MIN]))
    );
    assert_eq!(
        batch.column("unsigned_int"),
        Some(&PointColumn::U32(vec![60_000, u32::MAX]))
    );
    assert_eq!(batch.column("x"), Some(&PointColumn::F32(vec![1.5, -0.0])));
    assert_eq!(
        batch.column("time"),
        Some(&PointColumn::F64(vec![-2.25, 3.25]))
    );
    assert_eq!(
        batch.metadata().sensor_timestamp(),
        Timestamp::new(0, 0).unwrap()
    );
    assert_eq!(batch.metadata().frame_id(), "");
    assert!(!batch.metadata().is_dense());
}

#[test]
fn all_modes_probe_before_materialization_and_preserve_unknown_property_order() {
    for (fixture, encoding) in [
        (ASCII, Encoding::Ascii),
        (LITTLE, Encoding::BinaryLittleEndian),
        (BIG, Encoding::BinaryBigEndian),
    ] {
        let reader = Reader::new(fixture).unwrap();
        assert_eq!(reader.plan().encoding(), encoding);
        assert_eq!(reader.plan().vertex_count(), 2);
        assert_eq!(reader.plan().record_bytes(), 26);
        assert_eq!(
            reader.plan().materialization_bytes(),
            52 + 8 * std::mem::size_of::<PointColumn>()
        );

        let required = reader.plan().materialization_bytes();
        let error = Reader::new(fixture)
            .unwrap()
            .read(MaterializationBudget::new(required - 1))
            .unwrap_err();
        assert!(matches!(error, ply::Error::BudgetExceeded { .. }));

        let batch = reader.read(MaterializationBudget::new(required)).unwrap();
        assert_schema_and_values(&batch);
    }
}

#[test]
fn read_plan_feeds_the_common_memory_planner_before_execution() {
    let reader = Reader::new(LITTLE).unwrap();
    let requirements = reader.plan().pipeline_memory_requirements().unwrap();
    let job = JobSpec::extract(
        SourceSpec::file("cloud.ply").unwrap(),
        "static",
        FrameSelector::Index(0),
        Destination::stdout(),
    )
    .unwrap();
    let planned = Planner::new()
        .plan(job.clone(), requirements, u64::MAX)
        .unwrap();
    assert_eq!(
        planned.memory().breakdown().materialization_bytes(),
        u64::try_from(reader.plan().materialization_bytes()).unwrap()
    );
    assert!(
        Planner::new()
            .plan(job, requirements, planned.memory().peak_bytes() - 1)
            .is_err()
    );
}

#[test]
fn reviewed_goldens_have_independently_decodable_headers_and_payloads() {
    let (ascii_header, ascii_body) = split_header(ASCII);
    assert_eq!(ascii_header, expected_header("ascii"));
    let rows: Vec<Vec<&str>> = std::str::from_utf8(ascii_body)
        .unwrap()
        .lines()
        .map(|line| line.split_ascii_whitespace().collect())
        .collect();
    assert_eq!(
        rows,
        [
            ["-1", "2", "-300", "400", "-50000", "60000", "1.5", "-2.25"],
            [
                "-128",
                "255",
                "-32768",
                "65535",
                "-2147483648",
                "4294967295",
                "-0",
                "3.25"
            ],
        ]
    );

    for (fixture, encoding, little) in [
        (LITTLE, "binary_little_endian", true),
        (BIG, "binary_big_endian", false),
    ] {
        let (header, body) = split_header(fixture);
        assert_eq!(header, expected_header(encoding));
        assert_eq!(body.len(), 52);
        let first = &body[..26];
        assert_eq!(first[0] as i8, -1);
        assert_eq!(first[1], 2);
        let u16_at = |offset| {
            let bytes = first[offset..offset + 2].try_into().unwrap();
            if little {
                u16::from_le_bytes(bytes)
            } else {
                u16::from_be_bytes(bytes)
            }
        };
        let u32_at = |offset| {
            let bytes = first[offset..offset + 4].try_into().unwrap();
            if little {
                u32::from_le_bytes(bytes)
            } else {
                u32::from_be_bytes(bytes)
            }
        };
        let u64_at = |offset| {
            let bytes = first[offset..offset + 8].try_into().unwrap();
            if little {
                u64::from_le_bytes(bytes)
            } else {
                u64::from_be_bytes(bytes)
            }
        };
        assert_eq!(u16_at(2) as i16, -300);
        assert_eq!(u16_at(4), 400);
        assert_eq!(u32_at(6) as i32, -50_000);
        assert_eq!(u32_at(10), 60_000);
        assert_eq!(u32_at(14), 1.5_f32.to_bits());
        assert_eq!(u64_at(18), (-2.25_f64).to_bits());
    }
}

#[test]
fn writer_matches_reviewed_goldens_in_every_mode() {
    let batch = Reader::new(LITTLE)
        .unwrap()
        .read(MaterializationBudget::new(usize::MAX))
        .unwrap();
    for (encoding, expected) in [
        (Encoding::Ascii, ASCII),
        (Encoding::BinaryLittleEndian, LITTLE),
        (Encoding::BinaryBigEndian, BIG),
    ] {
        let mut actual = Vec::new();
        ply::write(&mut actual, &batch, encoding).unwrap();
        assert_eq!(actual, expected);
    }
}

#[test]
fn malformed_fixtures_are_rejected() {
    for fixture in [
        include_bytes!("fixtures/malformed/ply-list-properties-are-unsupported.ply").as_slice(),
        include_bytes!("fixtures/malformed/ply-int64-properties-are-unsupported.ply").as_slice(),
        include_bytes!("fixtures/malformed/ply-format-endianness-must-be-known.ply").as_slice(),
        include_bytes!("fixtures/malformed/ply-non-vertex-elements-are-lossy.ply").as_slice(),
    ] {
        assert!(Reader::new(fixture).is_err());
    }
    let reader = Reader::new(
        include_bytes!("fixtures/malformed/ply-binary-payload-must-not-be-truncated.ply")
            .as_slice(),
    )
    .unwrap();
    assert!(matches!(
        reader.read(MaterializationBudget::new(usize::MAX)),
        Err(ply::Error::TruncatedPayload { .. })
    ));

    let mut trailing = LITTLE.to_vec();
    trailing.push(0);
    assert!(matches!(
        Reader::new(trailing.as_slice())
            .unwrap()
            .read(MaterializationBudget::new(usize::MAX)),
        Err(ply::Error::TrailingData)
    ));

    let oversized = format!(
        "ply\nformat ascii 1.0\ncomment {}\nelement vertex 0\nproperty float x\nend_header\n",
        "x".repeat(ply::MAX_HEADER_BYTES)
    );
    assert!(matches!(
        Reader::new(oversized.as_bytes()),
        Err(ply::Error::HeaderTooLarge)
    ));
}

#[test]
fn scalar_type_aliases_map_to_the_same_common_primitives() {
    let input = b"ply\nformat ascii 1.0\nelement vertex 1\n\
property int8 a\nproperty uint8 b\nproperty int16 c\nproperty uint16 d\n\
property int32 e\nproperty uint32 f\nproperty float32 g\nproperty float64 h\n\
end_header\n-1 2 -3 4 -5 6 7.5 8.25\n";
    let reader = Reader::new(input.as_slice()).unwrap();
    let primitives: Vec<_> = reader
        .plan()
        .schema()
        .fields()
        .iter()
        .map(|field| field.primitive())
        .collect();
    assert_eq!(
        primitives,
        [
            PrimitiveType::I8,
            PrimitiveType::U8,
            PrimitiveType::I16,
            PrimitiveType::U16,
            PrimitiveType::I32,
            PrimitiveType::U32,
            PrimitiveType::F32,
            PrimitiveType::F64,
        ]
    );
    reader.read(MaterializationBudget::new(usize::MAX)).unwrap();
}

fn one_field_batch(
    field: PointField,
    dimensions: PointDimensions,
    column: PointColumn,
) -> PointBatch {
    PointBatch::new(
        Arc::new(PointSchema::new(vec![field]).unwrap()),
        Arc::new(PointFrameMetadata::new(
            Timestamp::new(0, 0).unwrap(),
            "",
            false,
        )),
        dimensions,
        vec![column],
    )
    .unwrap()
}

#[test]
fn writer_rejects_lossy_mappings_before_output() {
    let cases = [
        one_field_batch(
            PointField::new("samples", PrimitiveType::U8, 2, None).unwrap(),
            PointDimensions::new(1, 1).unwrap(),
            PointColumn::U8(vec![1, 2]),
        ),
        one_field_batch(
            PointField::new("clock", PrimitiveType::U64, 1, None).unwrap(),
            PointDimensions::new(1, 1).unwrap(),
            PointColumn::U64(vec![1]),
        ),
        one_field_batch(
            PointField::new("x", PrimitiveType::F32, 1, None).unwrap(),
            PointDimensions::new(1, 1).unwrap(),
            PointColumn::F32(vec![1.0]),
        ),
        one_field_batch(
            PointField::new("value", PrimitiveType::F32, 1, None).unwrap(),
            PointDimensions::new(1, 2).unwrap(),
            PointColumn::F32(vec![1.0, 2.0]),
        ),
    ];
    for batch in cases {
        let mut output = Vec::new();
        assert!(ply::write(&mut output, &batch, Encoding::BinaryLittleEndian).is_err());
        assert!(output.is_empty());
    }

    let metadata = PointBatch::new(
        Arc::new(
            PointSchema::new(vec![
                PointField::new("value", PrimitiveType::U8, 1, None).unwrap(),
            ])
            .unwrap(),
        ),
        Arc::new(PointFrameMetadata::new(
            Timestamp::new(1, 0).unwrap(),
            "map",
            true,
        )),
        PointDimensions::new(1, 1).unwrap(),
        vec![PointColumn::U8(vec![1])],
    )
    .unwrap();
    let mut output = Vec::new();
    assert!(matches!(
        ply::write(&mut output, &metadata, Encoding::BinaryLittleEndian),
        Err(ply::Error::UnrepresentableMetadata)
    ));
    assert!(output.is_empty());

    let nan = one_field_batch(
        PointField::new("value", PrimitiveType::F32, 1, None).unwrap(),
        PointDimensions::new(1, 1).unwrap(),
        PointColumn::F32(vec![f32::from_bits(0x7fc0_1234)]),
    );
    let mut output = Vec::new();
    assert!(matches!(
        ply::write(&mut output, &nan, Encoding::Ascii),
        Err(ply::Error::NonFiniteAscii { .. })
    ));
    assert!(output.is_empty());

    let mut binary = Vec::new();
    ply::write(&mut binary, &nan, Encoding::BinaryLittleEndian).unwrap();
    assert!(binary.ends_with(&0x7fc0_1234_u32.to_le_bytes()));
}
